### ISSUE TITLE
Extra tab (gauges) not on http://FLM-IP/#/

### ISSUE THREAD

**Issue by Ryton** [gebhardm/flmlocal#1]
Unfortunately, I didn't manage get this running as expected -yet- on a FL02B with firmware 244. 

The data/gauges/graphs ARE available now, directly through URLs such as as http://IP/gauge.html (or graph/panel), so the under-the-hood functionality is ok (which is great!).

But, the additional tab (gauges, as you show in a screenshot) isn't appearing in the main webpage for me at the Flukso-ip (http://FLM-IP/#/).

I followed your walktrough: downloaded and scp'd the /www dir, and rebooted. 
If I ssh to the FLM and open index.html, I see the new code for the gauges tabs, but for some reason its not showing up yet... 
Are there any steps i forgot? (or any additional data I should provide ?)

PS: The flmdisplay with name functionality works flawlessly!  (with adjusted fluksod.lua). 
Kudos for this!

**Comment by gebhardm** [comment]
No, there should be no extra step necessary. Did you perform a browser refresh, if something is kept in the cache?

**Comment by Ryton** [comment]
On any another computer on the network, the tabs (and names ) are there, thus must be browser cache indeed. 
Thanks for the pointer, and the impressive implementation

**Comment by Ryton** [comment]
update: i think it had to do with login privileges. i need to log in with user name & password on the main page, before the data becomes available.

**Comment by gebhardm** [comment]
The local visualization does not use the login privileges; so there is actually no login required.
