### ISSUE TITLE
Publication of sensor "name" if no /device/config/sensor description available.

### ISSUE THREAD

**Issue by Ryton** [gebhardm/flmlocal#5]
On the Panel & Gauge pages, data for custom (non-FLM-sensors) published over mqtt in the topic "/sensor/name/gauge/" appears correctly with my custom sensors, but their name appears empty ("").

I think its caused by the fact that your scripts subscribe to "/device/+/config/sensor" for a conversion between sensor name and device/sensor "function" and "type".

I'm planning to a publishing of those there, to make the names appear, but it could/would be usefull to include a fallback to the sensor name, instead of an empty string, if config/sensor is missing.

**Comment by gebhardm** [comment]
An empty name should not happen as when there is no "function" published through the "device" topic then "name" and "id" are taken identically.
See, for example, panel.js, lines 113ff.

```
        if (sIndex[0] == null) {
        sensor.id = sensorId;
        sensor.name = sensorId;
```

What is the format of your customer sensor publication? I use the one as described in the [ReadMe.md](https://github.com/gebhardm/flmlocal/blob/master/README.md) with an Arduino (ref to [energyhacks/AVRNetIOduino](https://github.com/gebhardm/energyhacks/tree/master/AVRNetIOduino/AVRNetIO_MQTT_DS_DHT)) - and as you can see, there are names present and I publish no "device" topic for this...

**Comment by gebhardm** [comment]
Just rechecked everything; it works exactly as described in the [ReadMe:Show arbitrary sensors](https://github.com/gebhardm/flmlocal/blob/master/README.md#show-arbitrary-sensors) section; there I wrote

> Note that here the `<sensor id>` is taken as name as long as you are not publishing any device configuration topic with id, name and if enabled (other parameters are currently not used, like "class" and "type", but may in the future).

So, check your published sensor topic, please.

**Comment by Ryton** [comment]
Thanks for the link to that readme. Didn't see that page/manual before. Very well documented example!

But, the weirdness continues: 
Using MQTT spy, i see that the messages ARE published correctly. I get following response from the FLM (mqqt browser) for my "newly" published sensors:

topic: /sensor/retour/gauge
message: [1434307324,21.937,"degC"]

For a build-in sensor, that is: 
topic /sensor/<gas sensor id>/gauge
data: [1434307515,74444,"L/day"]

Seems quite alike to me. Even if i round my temperature to ints (no comma), i get the same result (no extra gauge in gauge panel). 

HOWEVER, now that I've added the device/config string for just one of the sensors (the "retour" sensor), this one DOES show up. But with its <id>, below the sensor, NOT its <function> name as given in the device/+/config... The rest of the sensors still doesnt show up, although they publish exactly the same sensor/<id>/gauge topic & data structure...

topic /device/rapie/config/sensor 
data: { "1":{ "id":"retour","function":"TwRetour","enable"="1"} }
This seems quite comparable to me, agains a FLM sensor:
data:  {..., "4":{"id":"<id>","class":"pulse","function":"Total Gas","port":[4],"constant":10,"type":"gas","enable":1,"counter":<totvalue>}, .... }]

Thus: Weirdness still there.

But, I can live with it, i'll add config data for all 3 sensors, and call it a day :-)
I'll keep you posted if other weirdness pops up.

**Comment by gebhardm** [comment]
Hopefully this was just a copy error for the built-in sensor (topic /sensor//gauge) as this has no id; the retour-sensor looks O.K.<br>
Honestly, I am a bit puzzled by your explanation, as I do not really understand what you actually do as you jump between different aspects: "names", "values", "extra gauges" etc.

The payload internally is handled as string, so there is code-wise no difference on comma or not in vlaues (a DS18S20 sends with "point"); use the browser's debug capabilities to set a breakpoint at the position the message payload is passed on (e.g. [gauge.js, line 74](https://github.com/gebhardm/flmlocal/blob/master/www/scripts/controllers/gauge.js#L74)) - this is the only chance to see what really happens; there are so many different variants out there that you can only look for yourself (different browsers behave very differently, also on different devices); also set a breakpoint at [gauge.js, line 118](https://github.com/gebhardm/flmlocal/blob/master/www/scripts/controllers/gauge.js#L118) to see what is transferred as value.

You may also play with fake messages set up manually using mosquitto_pub; this is how I found out the way to convince the FLM.

By the way: All my stuff is documented like in the ReadMe - have you ever looked through the repository on Github?!

**Comment by Ryton** [comment]
Dear Marcus,

In response to previous post:

> > a copy error for the built-in sensor (topic /sensor//gauge) 
> > Yes, should have been /sensor/<sensorid>/gauge indeed.
> > 
> >  have you ever looked through the repository on Github?!
> > Yes, i did read your readme's on FLM-display & combined, and skimmed through large chuncks of code to -try to- understand it, as i'm no programmer by eductation. I just missed that part/version of the readme in the FLM-local repository, on mqtt topic/payload for sensor name configuration.
> > 
> > Honestly, I am a bit puzzled by your explanation, as I do not really understand what you actually 
> > do as you jump between different aspects: "names", "values", "extra gauges" etc.
> > I am sorry if i was unclear. 
> > With <id> i mean the name used in the /sensor/+/gauges
> > With <name> i mean the name stated in the config, and which should appear below the gauges
> > With <extra gauges> I mean the non-FLM mqtt messages. 

On topic: 
Still much weirdness occuring on my FLM itself...
It might be best for me do a full delete & pull of the github base.

Reason: The html page that the FLM is serving, seems NOT to be the html in /www/index.html, as parts of its code is ignored in the shown page. eg. there is NO Chart-menu entry, while there is in the code.
From MQTT point of view, all seems ok, since i can see the packets in the mqtt spy.

Thus, probably its a (self-induced) HTML-side & FLM-side error. 
Sorry to bother you with it, I'll try to solve it myself.

**Comment by gebhardm** [comment]
Don't mind - if I can be of help, I'll do my best; the better the issue description, the better any potential root cause analysis. With respect to "i'm no programmer by eductation" - there is no programming education as computer science is no science ;-) (I see programming as a tool only to express the algorithms I am thinking about, for I am a Mathematician by heart)

Note that AngularJS is quite tricky; this took me also some time to figure out how the interconnect works. The changed parts in the index.html together with the app.js are actually only the menu references; these you may add also in an editor manually.

Please also note that my FLM is on v244, so this is also to be taken care of if Bart did changes in-between (but I am not aware of such)

**Comment by Ryton** [comment]
- my FLM is on v244
  My FLM is also on v244. But for some reason, with the FLM-local upload, the GRAPH menu doesn't appear and isn't accessible (on <FLM-ip>/#/chart) , while part panel & gauge buttons are there & are functional.  Thus, my current hypothesis is that the FLM is hosting some locally cached version of the index.html or website, or from another directory. Will perform some break/echo tests tonight.
-  computer science is no science ;-) 
  Haha, I'll use this against my friends with a CS education! :-D ;-)
- I see programming as a tool only to express the algorithms I am thinking about
  Sounds like a healthy attitude! Thats also why I'm using python for this project, instead of html/node.js: to learn from it, and to use python for data analysis afterwards.

**Comment by gebhardm** [comment]
The FLM does not cache, but the browser - so always make sure that the browser cache is empty as all the index.html and *.js files are uploaded to your frontend (this raised not only one issue in the past - therefore I always clean everything after doing web-related code changes)
