### ISSUE TITLE
(Feature-request) query & publish json to mqtt on FLM-local

### ISSUE THREAD

**Issue by Ryton** [gebhardm/flmlocal#7]
Hi @gebhardm , 

Would it be feasible / useful to integrate (call, publish and visualise) an external json data query (web-API) on FLM-local as well?  
Or would it be easier to just visualise an API request content in a (separate) visualisation?
Or query/ publish it in a background process?

If i understand the "arbitrary sensor capability" of flm-local correctly, this code can natively visualise any arbitrary sensor published on the mqtt server, in the /sensor/<id>/gauge topic while the website is active, with different formats?

Application:
I'd like to include the output from an API, returning a json, preferably on the always persistent mqtt /FLM local visualisation.

**Comment by gebhardm** [comment]
Hello Ryton,
it is feasible and useful in the sense that you have a running visualizer on the FLM, so why put a second one somewhere else. You may directly show results by utilizing the same json format as sent/used by the FLM; see https://github.com/gebhardm/energyhacks/tree/master/ESP8266 for an example - as long as the format fits to one existing visualization, you may use it directly. But note that this info is not stored on the FLM, but displayed only. It works fine for temperatur and will for any other "gauge like" information. For everything else you may alter/fork the code for your purposes. The "idea" should be clear from the setup as the FLM "just" displays additional html pages that do something meaningful implemented by Javascript.
As I have no use case, I actually won't invest here.
Best regards
Markus

**Comment by Ryton** [comment]
ok, thanks. will make my own fork as a hobby project then :-)
